#include <stdio.h>

int main() {
    int input;
    printf("請輸入一個數: ");
    scanf("%d", &input);
    
    int binary[32]; // 
    int index = 0; // 
    
    // 
    while (input > 0) {
        binary[index] = input % 2; // 
        input = input / 2; // 
        index++; //
    }
    
    printf("轉換為二進位數: ");
    // 
    for (int i = index - 1; i >= 0; i--) {
        printf("%d", binary[i]);
    }
    
    return 0;
}
